version: '2'
services:
    wiki:
        build: .
        # you need to run "export COOKIESECRET=iecheeBeipohr7aehu0goog6wugheich" before invoking "docker-compose up"
        command: ["wiki", "--autoseed", "--security_type", "friends", "--cookieSecret", "${COOKIESECRET}", "--session_duration", "14"]
        environment:
            COOKIESECRET: "iecheeBeipohr7aehu0goog6wugheich"
            NODE_ENV: "production"
        volumes:
            - "/srv/wiki/:/root/.wiki/:z"
        ports:
            - "3000:3000"

